# Generated by Django 3.2.8 on 2022-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_regression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alpha', models.IntegerField()),
                ('name2', models.CharField(max_length=50)),
                ('alpha2', models.IntegerField()),
            ],
        ),
    ]
